# Generated by Django 4.2.5 on 2023-09-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0002_video_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uploaded_by',
        ),
    ]
