# Generated by Django 4.2.5 on 2023-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0003_remove_video_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
