# Generated by Django 4.2.5 on 2023-09-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0004_video_user_id_alter_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
