# Generated by Django 4.2.5 on 2023-09-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0007_like_video_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
