# Generated by Django 4.2.5 on 2023-09-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0010_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
